version: '3.8'  # Updated version is recommended

services:
  core:
    container_name: node_server
    hostname: core
    build:
      context: .
    env_file:
      - .env
    environment:
      - UPLOAD_DIR=/app/uploads
      - BASE_URL=${BASE_URL} 
    ports:
      - '3000:3000'
    volumes:
      - ./uploads:/app/uploads  # Ensure file uploads persist and are accessible
    depends_on:
      - redis

  redis:
    container_name: redis_container
    image: 'redis:latest'
    hostname: redis

volumes:
  uploads_volume:
